<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('payway_callback_histories', function (Blueprint $table) {
            $table->id();
            $table->string('tran_id', 20)->comment('Payment transaction ID generated by PayWay');
            $table->unsignedInteger('apv')->nullable()->comment('Transaction approval code (6 digits)');
            $table->string('status', 10)->nullable()->comment('Callback status code, e.g. 00 = success');
            $table->string('merchant_ref_no', 100)->nullable()->comment('Merchant payment reference number');
            $table->json('raw_payload')->nullable()->comment('Full raw POST payload received from PayWay');
            $table->string('ip_address', 45)->nullable();
            $table->string('user_agent', 255)->nullable();
            $table->boolean('is_processed')->default(false)->comment('Whether the callback was successfully processed');
            $table->timestamp('processed_at')->nullable();
            $table->text('processing_notes')->nullable()->comment('Notes or errors from processing');
            $table->timestamps();

            $table->index('tran_id');
            $table->index('merchant_ref_no');
            $table->index('status');
            $table->index('is_processed');
            $table->index('created_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('payway_callback_histories');
    }
};
